name: robot_learning
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - matplotlib
  - pytest
  - pip:
      - --index-url https://download.pytorch.org/whl/cu130
      - torch==2.12.1
