"""Unit tests for V, Q, Advantage, and Monte Carlo estimates."""

import numpy as np
import pytest

from robot_learning.value_estimation import (
    analyze_policy_values,
    estimate_discrete_action_values,
)


def test_policy_value_is_probability_weighted_action_value() -> None:
    """V must average Q values under the current policy probabilities."""
    analysis = analyze_policy_values(
        action_values=np.asarray([1.0, 1.8]),
        action_probabilities=np.asarray([0.75, 0.25]),
    )

    assert analysis.state_value == pytest.approx(1.2)
    np.testing.assert_allclose(analysis.advantages, [-0.2, 0.6])


def test_policy_weighted_advantage_has_zero_mean() -> None:
    """Advantages are deviations from the policy's own average value."""
    probabilities = np.asarray([0.75, 0.25])
    analysis = analyze_policy_values(
        action_values=np.asarray([1.0, 1.8]),
        action_probabilities=probabilities,
    )

    assert np.dot(probabilities, analysis.advantages) == pytest.approx(0.0)


def test_monte_carlo_action_values_average_returns_by_action() -> None:
    """Q estimates must not mix returns generated by different first actions."""
    estimates, counts = estimate_discrete_action_values(
        action_ids=np.asarray([0, 1, 1, 0, 1]),
        returns=np.asarray([1.0, 3.6, -3.6, 1.0, 3.6]),
        action_count=2,
    )

    np.testing.assert_array_equal(counts, [2, 3])
    np.testing.assert_allclose(estimates, [1.0, 1.2])


@pytest.mark.parametrize(
    ("values", "probabilities"),
    [
        (np.asarray([]), np.asarray([])),
        (np.asarray([1.0]), np.asarray([0.5, 0.5])),
        (np.asarray([1.0, 2.0]), np.asarray([0.8, 0.8])),
        (np.asarray([1.0, 2.0]), np.asarray([1.1, -0.1])),
    ],
)
def test_invalid_policy_value_inputs_are_rejected(
    values: np.ndarray,
    probabilities: np.ndarray,
) -> None:
    """Invalid policy distributions must not produce plausible values."""
    with pytest.raises(ValueError):
        analyze_policy_values(values, probabilities)


def test_action_value_estimate_requires_every_action_to_be_sampled() -> None:
    """An unseen action has no Monte Carlo Q estimate in the current data."""
    with pytest.raises(ValueError, match="every action"):
        estimate_discrete_action_values(
            action_ids=np.asarray([0, 0]),
            returns=np.asarray([1.0, 1.0]),
            action_count=2,
        )
