"""Control the simulated camera joint with a PID controller."""

import rclpy
from rclpy.node import Node
from sensor_msgs.msg import JointState

from point_robot_ros.control import PIDController
from point_robot_ros.kinematics import CAMERA_YAW_LIMIT


class CameraPIDController(Node):
    """Publish camera joint states generated by PID control."""

    def __init__(self) -> None:
        super().__init__("camera_pid_controller")

        self.declare_parameter("target_yaw", 1.0)
        self.declare_parameter("initial_yaw", 0.0)
        self.declare_parameter("kp", 2.0)
        self.declare_parameter("ki", 0.5)
        self.declare_parameter("kd", 0.0)
        self.declare_parameter("max_velocity", 1.0)
        self.declare_parameter("integral_limit", 0.5)
        self.declare_parameter("control_period", 0.02)

        self._control_period = float(
            self.get_parameter("control_period").value
        )
        self._current_yaw = float(
            self.get_parameter("initial_yaw").value
        )

        self._controller = PIDController(
            kp=float(self.get_parameter("kp").value),
            ki=float(self.get_parameter("ki").value),
            kd=float(self.get_parameter("kd").value),
            max_command=float(
                self.get_parameter("max_velocity").value
            ),
            integral_limit=float(
                self.get_parameter("integral_limit").value
            ),
        )

        self._publisher = self.create_publisher(
            JointState,
            "/joint_states",
            10,
        )
        self._timer = self.create_timer(
            self._control_period,
            self._update_control,
        )

        self._step_count = 0

        self.get_logger().info(
            "Camera PID controller started at yaw=%.3f"
            % self._current_yaw
        )

    def _update_control(self) -> None:
        requested_target = float(
            self.get_parameter("target_yaw").value
        )
        target_yaw = max(
            -CAMERA_YAW_LIMIT,
            min(CAMERA_YAW_LIMIT, requested_target),
        )

        velocity_command = self._controller.update(
            target=target_yaw,
            current=self._current_yaw,
            dt=self._control_period,
        )

        next_yaw = (
            self._current_yaw
            + velocity_command * self._control_period
        )
        next_yaw = max(
            -CAMERA_YAW_LIMIT,
            min(CAMERA_YAW_LIMIT, next_yaw),
        )

        actual_velocity = (
            next_yaw - self._current_yaw
        ) / self._control_period
        self._current_yaw = next_yaw

        message = JointState()
        message.header.stamp = self.get_clock().now().to_msg()
        message.name = ["camera_joint"]
        message.position = [self._current_yaw]
        message.velocity = [actual_velocity]
        message.effort = []

        self._publisher.publish(message)

        self._step_count += 1
        if self._step_count % 25 == 0:
            self.get_logger().info(
                "target=%.3f current=%.3f velocity=%.3f"
                % (
                    target_yaw,
                    self._current_yaw,
                    actual_velocity,
                )
            )


def main(args: list[str] | None = None) -> None:
    rclpy.init(args=args)
    node = CameraPIDController()

    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        try:
            node.destroy_node()
        except KeyboardInterrupt:
            pass
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == "__main__":
    main()
